<?php

namespace AppBundle\Repository;

/**
 * CodificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodificationRepository extends \Doctrine\ORM\EntityRepository
{
}
