<?php

namespace AppBundle\Repository;

/**
 * CorridorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorridorRepository extends \Doctrine\ORM\EntityRepository
{
}
