<?php

namespace AppBundle\Repository;

/**
 * HasConstraintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasConstraintRepository extends \Doctrine\ORM\EntityRepository
{
}
