app_corridor:
    resource: "@AppBundle/Controller/CorridorController.php"
    type:     annotation

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation

buildings:
    type:     rest
    resource: AppBundle\Controller\BuildingController